#!/bin/bash

# -----------------------------------------------------------------------------
# Author: Tal Aharon
# License: GPL 2.x
#
# Purpose: Create a new C source file with a given name in the current directory.
#
# Usage: cfile <name of the file>
#
# Arguments:
#   - <name of the file>: The name of the new C source file to create.
#
# Description:
#   The `cfile` script takes the name of a new C source file as an argument and 
#   creates a new file in the current directory with that name. The new file is 
#   initialized with the contents of an example C source file from the user's 
#   home directory. The script then opens the new file for editing.
#
# Examples:
#   Create a new C source file called `my_file.c` and open it for editing:
#   $ cfile my_file
#
# Notes:
#   - The example C source file is assumed to be located in the user's home directory.
#
# -----------------------------------------------------------------------------

# Exit immediately if any command fails
set -e
if [ -z "$1" ]; then
    echo "Please provide a name for a new C file: cfile <name>"
    exit 1
fi

template_file_name="test_file.c"
path_to_c_template=$(find "$(echo "$CHOSEN_GIT" | tr ':' ' ')" -type f -name "$template_file_name")

if [ ! -f "$path_to_c_template" ]; then
    echo "Template C source file '$template_file_name' not found."
    exit 1
fi

new_file_name="$1.c"

if [ -f "$new_file_name" ]; then
    echo "File '$new_file_name' already exists. Choose a different name."
    exit 1
fi

cat "$path_to_c_template" > "$new_file_name"
code "$new_file_name"
exit 0